---
version: "3"

services:
  lufi:
    container_name: lufi
    build: .
    ports:
      - 9999:8081
    volumes:
      - "data:/usr/lufi/files"
      - ./camba_theme:/usr/lufi/themes/camba
    restart: "unless-stopped"
    env_file:
      .env
volumes:
  data: